pipeline:
  name: ci-github-trigger
  identifier: cigithubtrigger
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_477
        repoName: all_stages
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: large
              imageSpec:
                imageName: ubuntu-22
          execution:
            steps:
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gcp477
                    host: us-central1-docker.pkg.dev
                    projectID: project-cb80b961-01f1-443f-bfb
                    imageName: " demo-repo1"
                    tags:
                      - "1.11"
