pipeline:
  name: iac-477
  identifier: iac477
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: mvn
        identifier: mvn
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: small
              imageSpec:
                imageName: ubuntu-22
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: docker_hub_477
                    image: maven:3.9-eclipse-temurin-21
                    shell: Sh
                    command: |-
                      mvn clean package -DskipTests -Dcheckstyle.skip=true
                      mvn clean package
  properties:
    ci:
      codebase:
        connectorRef: github_477
        repoName: gharness_ci
        build: <+input>
